- name: add webupd8 ppa
  apt_repository: repo='ppa:webupd8team/java'
  become: true

- name: update
  shell: apt-get update
  become: true

- name: auto accept oracle jdk license
  shell: echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections
  become: true

- name: install java8
  shell: apt-get install -y oracle-java8-installer oracle-java8-set-default ca-certificates
  become: true
